name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install node
        id: node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm
      - name: Install packages
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm test
  release:
    runs-on: ubuntu-latest
    needs: [test]
    if: "${{ github.repository_owner == 'marko-js' && github.event_name == 'push' }}"
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm
      - name: Install packages
        run: npm ci
      - name: Run release
        uses: changesets/action@v1
        with:
          version: npm run @ci:version
          publish: npm run @ci:release
          commit: "[ci] release"
          title: "[ci] release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
